FROM azuresdk/azure-cli-python
MAINTAINER chvugrin@microsoft.com

WORKDIR "/opt/azure-vmtest/"

COPY  cert.pem  /opt/azure-vmtest/
COPY  createvm.py  /opt/azure-vmtest/
COPY  createvm.sh  /opt/azure-vmtest/
COPY  azurevm.json  /opt/azure-vmtest/
COPY  login.sh /opt/azure-vmtest/

RUN ["pip","install","redis"]
RUN ["pip","install","azure-cosmosdb-table"]

ENV AZURE_USER='http://XXX_SOLUTION_NAME_XXX'
ENV AZURE_PWD='XXX_PASSWORD_XXX'
ENV AZURE_TENANT=XXX_TENANTID_XXX

CMD ["/opt/azure-vmtest/login.sh"]

#ENTRYPOINT [ "./provision.sh" ]
