apiVersion: v1
kind: ReplicationController
metadata:
  name: vmcr8-weathermap
spec:
  replicas: 3
  selector:
    app: vmcr8er-weatherma
  template:
    metadata:
      name: vmcr8er-weatherma
      labels:
        app: vmcr8er-weatherma
    spec:
      containers:
      - name: vmcr8er-weatherma
        image: vmcr8tester.azurecr.io/weathermap:latest
        ports:
        - containerPort: 8080
